spring:
  profiles:
    active: dev # 기본 환경 선택
  datasource:    hikari:      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none    
mybatis:  config-location: classpath:mybatis-config.xml
  
graphql:
  spqr:
    relay:
      connection-check-relaxed: false
    ws:
      enabled: false
      keep-alive:
        enabled: false
    gui:
      enabled: true
      target-endpoint: /gapi
    http:
      endpoint: /gapi  

web.jwt:
  issuer: http://localhost
  signing-key: skpayadminapisign
  expire-time: 604800
  refresh-expire-time: 604800           
  
# LOCAL 환경
---
# Server
server:  port: 8080

# Spring
spring:
  application:    name: WEB_LOCAL
  profiles: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:oracle
    username: dev
    password: 1234    dbcp2:      test-while-idle: true      validation-query: SELECT 1 
    

# DEV 환경
---
# Server
server:
  port: 8080

# Spring
spring:
  application:
    name: WEB_DEV
  profiles: dev
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:oracle
    username: dev
    password: 1234
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1     